# Generated by Django 5.0.6 on 2024-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log_time', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=20)),
                ('bias', models.IntegerField()),
            ],
        ),
    ]
